update_aams: refactoring

diff --git a/update_aams b/update_aams
--- a/update_aams
+++ b/update_aams
@@ -1,32 +1,35 @@
 #!/bin/sh -e
 
-URL_aams1='https://www1.agenziadoganemonopoli.gov.it/files_siti_inibiti/elenco_siti_inibiti.txt'
-URL_aams2='https://www1.agenziadoganemonopoli.gov.it/files_siti_inibiti/file_controllo.txt'
-FILE_aams1='tmp/elenco_siti_inibiti.txt'
-FILE_aams2='tmp/elenco_siti_inibiti.sha-256'
-
 CURL_OPTS_aams=''
 
-##############################################################################
 # be verbose when stdout is a tty
 if [ ! -t 0 ]; then
   CURL_OPTS_aams="$CURL_OPTS_aams --silent --show-error"
 fi
 
-## downloading ###############################################################
-curl --fail --location --remote-time $CURL_OPTS_aams \
-  --output $FILE_aams1.tmp $URL_aams1
-mv $FILE_aams1.tmp $FILE_aams1
+download_aams() {
+  local output=$1
 
-curl --fail --location --remote-time $CURL_OPTS_aams \
-  --output $FILE_aams2.tmp $URL_aams2
-mv $FILE_aams2.tmp $FILE_aams2
+  local FILE_aams1='tmp/elenco_siti_inibiti.txt'
+  local FILE_aams2='tmp/elenco_siti_inibiti.sha-256'
 
-if ! echo "$(cat $FILE_aams2) $FILE_aams1" | sha256sum --check --status; then
-  echo "Invalid SHA-256 checksum for $FILE_aams1!" >&2
-  exit 1
-fi
+  curl --fail --location --remote-time $CURL_OPTS_aams \
+    --output $FILE_aams1.tmp $URL_aams1
+  mv $FILE_aams1.tmp $FILE_aams1
 
-## parsing ###################################################################
-./parse_aams $FILE_aams1 lists/aams.new
+  curl --fail --location --remote-time $CURL_OPTS_aams \
+    --output $FILE_aams2.tmp $URL_aams2
+  mv $FILE_aams2.tmp $FILE_aams2
+
+  if ! echo "$(cat $FILE_aams2) $FILE_aams1" | sha256sum --check --status; then
+    echo "Invalid SHA-256 checksum for $FILE_aams1!" >&2
+    exit 1
+  fi
+
+  ./parse_aams $FILE_aams1 $output
+}
+
+URL_aams1='https://www1.agenziadoganemonopoli.gov.it/files_siti_inibiti/elenco_siti_inibiti.txt'
+URL_aams2='https://www1.agenziadoganemonopoli.gov.it/files_siti_inibiti/file_controllo.txt'
+download_aams lists/aams.new
 
